### ISSUE TITLE
error running test code

### ISSUE THREAD

**Issue by zizo9512** [MLSpeech/speech_yolo#3]
I have tried to run the test code using model uploaded by you, but I keep getting getting the following error

Traceback (most recent call last):
  File "F:\Download\speech_yolo-master\test_yolo.py", line 53, in <module>
    model, acc, epoch = load_model(model)
  File "F:\Download\speech_yolo-master\model_speech_yolo.py", line 112, in load_model
    arc_type = checkpoint['arc']
KeyError: 'arc'

**Comment by Tzeviya** [comment]
Hi, thank you for opening this issue. We uploaded new models.
